description = 'Prototype actuator motors'

pvprefix = 'ESTIA-Sel1:MC-MCU-01:'

devices = dict(
    am1=device(
        'nicos_ess.devices.epics.motor.EpicsMotor',
        description='Eksma Actuator',
        motorpv=pvprefix + 'm1',
        errormsgpv=pvprefix + 'm1-MsgTxt',
        errorbitpv=pvprefix + 'm1-Err',
        reseterrorpv=pvprefix + 'm1-ErrRst',
    ),
    am2=device(
        'nicos_ess.devices.epics.motor.EpicsMotor',
        description='Eksma Actuator',
        motorpv=pvprefix + 'm2',
        errormsgpv=pvprefix + 'm2-MsgTxt',
        errorbitpv=pvprefix + 'm2-Err',
        reseterrorpv=pvprefix + 'm2-ErrRst',
    ),
    am3=device(
        'nicos_ess.devices.epics.motor.EpicsMotor',
        description='Eksma Actuator',
        motorpv=pvprefix + 'm3',
        errormsgpv=pvprefix + 'm3-MsgTxt',
        errorbitpv=pvprefix + 'm3-Err',
        reseterrorpv=pvprefix + 'm3-ErrRst',
    ),
    am4=device(
        'nicos_ess.devices.epics.motor.EpicsMotor',
        description='Eksma Actuator',
        motorpv=pvprefix + 'm4',
        errormsgpv=pvprefix + 'm4-MsgTxt',
        errorbitpv=pvprefix + 'm4-Err',
        reseterrorpv=pvprefix + 'm4-ErrRst',
    ),
    am5=device(
        'nicos_ess.devices.epics.motor.EpicsMotor',
        description='Eksma Actuator',
        motorpv=pvprefix + 'm5',
        errormsgpv=pvprefix + 'm5-MsgTxt',
        errorbitpv=pvprefix + 'm5-Err',
        reseterrorpv=pvprefix + 'm5-ErrRst',
    ),
    am6=device(
        'nicos_ess.devices.epics.motor.EpicsMotor',
        description='Eksma Actuator',
        motorpv=pvprefix + 'm6',
        errormsgpv=pvprefix + 'm6-MsgTxt',
        errorbitpv=pvprefix + 'm6-Err',
        reseterrorpv=pvprefix + 'm6-ErrRst',
    ),
    am7=device(
        'nicos_ess.devices.epics.motor.EpicsMotor',
        description='Eksma Actuator',
        motorpv=pvprefix + 'm7',
        errormsgpv=pvprefix + 'm7-MsgTxt',
        errorbitpv=pvprefix + 'm7-Err',
        reseterrorpv=pvprefix + 'm7-ErrRst',
    ),
    am8=device(
        'nicos_ess.devices.epics.motor.EpicsMotor',
        description='Eksma Actuator',
        motorpv=pvprefix + 'm8',
        errormsgpv=pvprefix + 'm8-MsgTxt',
        errorbitpv=pvprefix + 'm8-Err',
        reseterrorpv=pvprefix + 'm8-ErrRst',
    ),
    am9=device(
        'nicos_ess.devices.epics.motor.EpicsMotor',
        description='Eksma Actuator',
        motorpv=pvprefix + 'm9',
        errormsgpv=pvprefix + 'm9-MsgTxt',
        errorbitpv=pvprefix + 'm9-Err',
        reseterrorpv=pvprefix + 'm9-ErrRst',
    ),
    am10=device(
        'nicos_ess.devices.epics.motor.EpicsMotor',
        description='Eksma Actuator',
        motorpv=pvprefix + 'm10',
        errormsgpv=pvprefix + 'm10-MsgTxt',
        errorbitpv=pvprefix + 'm10-Err',
        reseterrorpv=pvprefix + 'm10-ErrRst',
    ),
    am11=device(
        'nicos_ess.devices.epics.motor.EpicsMotor',
        description='Eksma Actuator',
        motorpv=pvprefix + 'm11',
        errormsgpv=pvprefix + 'm11-MsgTxt',
        errorbitpv=pvprefix + 'm11-Err',
        reseterrorpv=pvprefix + 'm11-ErrRst',
    ),
    am12=device(
        'nicos_ess.devices.epics.motor.EpicsMotor',
        description='Eksma Actuator',
        motorpv=pvprefix + 'm12',
        errormsgpv=pvprefix + 'm12-MsgTxt',
        errorbitpv=pvprefix + 'm12-Err',
        reseterrorpv=pvprefix + 'm12-ErrRst',
    ),
    am13=device(
        'nicos_ess.devices.epics.motor.EpicsMotor',
        description='Eksma Actuator',
        motorpv=pvprefix + 'm13',
        errormsgpv=pvprefix + 'm13-MsgTxt',
        errorbitpv=pvprefix + 'm13-Err',
        reseterrorpv=pvprefix + 'm13-ErrRst',
    ),
    am14=device(
        'nicos_ess.devices.epics.motor.EpicsMotor',
        description='Eksma Actuator',
        motorpv=pvprefix + 'm14',
        errormsgpv=pvprefix + 'm14-MsgTxt',
        errorbitpv=pvprefix + 'm14-Err',
        reseterrorpv=pvprefix + 'm14-ErrRst',
    ),
    am15=device(
        'nicos_ess.devices.epics.motor.EpicsMotor',
        description='Eksma Actuator',
        motorpv=pvprefix + 'm15',
        errormsgpv=pvprefix + 'm15-MsgTxt',
        errorbitpv=pvprefix + 'm15-Err',
        reseterrorpv=pvprefix + 'm15-ErrRst',
    ),
    am16=device(
        'nicos_ess.devices.epics.motor.EpicsMotor',
        description='Eksma Actuator',
        motorpv=pvprefix + 'm16',
        errormsgpv=pvprefix + 'm16-MsgTxt',
        errorbitpv=pvprefix + 'm16-Err',
        reseterrorpv=pvprefix + 'm16-ErrRst',
    ),
    am17=device(
        'nicos_ess.devices.epics.motor.EpicsMotor',
        description='Eksma Actuator',
        motorpv=pvprefix + 'm17',
        errormsgpv=pvprefix + 'm17-MsgTxt',
        errorbitpv=pvprefix + 'm17-Err',
        reseterrorpv=pvprefix + 'm17-ErrRst',
    ),
    am18=device(
        'nicos_ess.devices.epics.motor.EpicsMotor',
        description='Eksma Actuator',
        motorpv=pvprefix + 'm18',
        errormsgpv=pvprefix + 'm18-MsgTxt',
        errorbitpv=pvprefix + 'm18-Err',
        reseterrorpv=pvprefix + 'm18-ErrRst',
    ),
)
