description = 'Selene1 mover motors'

pvprefix = 'PSI-ESTIARND:MC-MCU-01:'

devices = dict(
    mover_fl_re_us=device(
        'nicos_ess.devices.epics.pva.motor.EpicsMotor',
        description='Mtr1 Selene1 1-Mover FL-RE-US',
        motorpv=f'{pvprefix}Mtr1',
        errormsgpv=f'{pvprefix}Mtr1-MsgTxt',
        errorbitpv=f'{pvprefix}Mtr1-Err',
        reseterrorpv=f'{pvprefix}Mtr1-ErrRst',
        unit='degree',
        pollinterval=None,
        monitor=True,
        pva=True,
    ),
    mover_pr_re_ds=device(
        'nicos_ess.devices.epics.pva.motor.EpicsMotor',
        description='Mtr2 Selene1 1-Mover PR-RE-DS',
        motorpv=f'{pvprefix}Mtr2',
        errormsgpv=f'{pvprefix}Mtr2-MsgTxt',
        errorbitpv=f'{pvprefix}Mtr2-Err',
        reseterrorpv=f'{pvprefix}Mtr2-ErrRst',
        unit='degree',
        pollinterval=None,
        monitor=True,
        pva=True,
    ),
    mover_pr_li_ds=device(
        'nicos_ess.devices.epics.pva.motor.EpicsMotor',
        description='Mtr3 Selene1 1-Mover PR-LI-DS',
        motorpv=f'{pvprefix}Mtr3',
        errormsgpv=f'{pvprefix}Mtr3-MsgTxt',
        errorbitpv=f'{pvprefix}Mtr3-Err',
        reseterrorpv=f'{pvprefix}Mtr3-ErrRst',
        unit='degree',
        pollinterval=None,
        monitor=True,
        pva=True,
    ),
    mover_pr_li_us1=device(
        'nicos_ess.devices.epics.pva.motor.EpicsMotor',
        description='Mtr4 Selene1 2-Mover PR-LI-US-1',
        motorpv=f'{pvprefix}Mtr4',
        errormsgpv=f'{pvprefix}Mtr4-MsgTxt',
        errorbitpv=f'{pvprefix}Mtr4-Err',
        reseterrorpv=f'{pvprefix}Mtr4-ErrRst',
        unit='degree',
        pollinterval=None,
        monitor=True,
        pva=True,
    ),
    mover_pr_li_us2=device(
        'nicos_ess.devices.epics.pva.motor.EpicsMotor',
        description='Mtr5 Selene1 2-Mover PR-LI-US-2',
        motorpv=f'{pvprefix}Mtr5',
        errormsgpv=f'{pvprefix}Mtr5-MsgTxt',
        errorbitpv=f'{pvprefix}Mtr5-Err',
        reseterrorpv=f'{pvprefix}Mtr5-ErrRst',
        unit='degree',
        pollinterval=None,
        monitor=True,
        pva=True,
    ),
)
