description = 'NE9000 peristaltic pump'

pv_root = 'E04-SEE-FLUCO:NE9000-001:'

devices = dict(
    inside_diameter_9000=device(
        'nicos.devices.epics.EpicsAnalogMoveable',
        description='The Inside diameter of the syringe',
        readpv='{}DIAMETER'.format(pv_root),
        writepv='{}SET_DIAMETER'.format(pv_root),
        epicstimeout=3.0,
        abslimits=(0.1, 50),
    ),
    pump_volume_9000=device(
        'nicos.devices.epics.EpicsAnalogMoveable',
        description='The volume to be pumped',
        readpv='{}VOLUME'.format(pv_root),
        writepv='{}SET_VOLUME'.format(pv_root),
        epicstimeout=3.0,
        abslimits=(0.1, 50),
    ),
    pump_volume_units_9000=device(
        'nicos_ess.devices.epics.extensions.EpicsMappedMoveable',
        description='The volume units',
        readpv='{}VOLUME_UNITS'.format(pv_root),
        writepv='{}SET_VOLUME_UNITS'.format(pv_root),
        mapping={'μL': 0, 'mL': 1},
    ),
    pump_rate_9000=device(
        'nicos.devices.epics.EpicsAnalogMoveable',
        description='The pump rate',
        readpv='{}RATE'.format(pv_root),
        writepv='{}SET_RATE'.format(pv_root),
        epicstimeout=3.0,
        abslimits=(0.1, 50),
    ),
    pump_rate_units_9000=device(
        'nicos_ess.devices.epics.extensions.EpicsMappedMoveable',
        description='The rate units',
        readpv='{}RATE_UNITS'.format(pv_root),
        writepv='{}SET_RATE_UNITS'.format(pv_root),
        mapping={'μL / min': 0, 'mL / min': 1, 'μL / hr': 2, 'mL / hr': 3},
    ),
    pump_direction_9000=device(
        'nicos_ess.devices.epics.extensions.EpicsMappedMoveable',
        description='The pump direction',
        readpv='{}DIRECTION'.format(pv_root),
        writepv='{}SET_DIRECTION'.format(pv_root),
        mapping={'INF': 0, 'WDR': 1, 'REV': 2, 'STK': 3},
    ),
    volume_withdrawn_9000=device(
        'nicos.devices.epics.EpicsReadable',
        description='The volume withdrawn',
        readpv='{}VOLUME_WITHDRAWN'.format(pv_root),
        epicstimeout=3.0,
    ),
    volume_infused_9000=device(
        'nicos.devices.epics.EpicsReadable',
        description='The volume infused',
        readpv='{}VOLUME_INFUSED'.format(pv_root),
        epicstimeout=3.0,
    ),
    pump_status_9000=device(
        'nicos.devices.epics.EpicsReadable',
        description='The pump status',
        readpv='{}STATUS'.format(pv_root),
        lowlevel=True,
        epicstimeout=3.0,
    ),
    pump_message_9000=device(
        'nicos.devices.epics.EpicsStringReadable',
        description='The pump message',
        readpv='{}MESSAGE'.format(pv_root),
        lowlevel=True,
        epicstimeout=3.0,
    ),
    start_purge_9000=device(
        'nicos_ess.devices.epics.extensions.EpicsMappedMoveable',
        description='Start purging',
        readpv='{}PURGE'.format(pv_root),
        writepv='{}PURGE'.format(pv_root),
        mapping={'OFF': 0, 'ON': 1},
    ),
    start_pumping_9000=device(
        'nicos_ess.devices.epics.extensions.EpicsMappedMoveable',
        description='Start pumping',
        readpv='{}RUN'.format(pv_root),
        writepv='{}RUN'.format(pv_root),
        mapping={'OFF': 0, 'ON': 1},
    ),
    pause_pumping_9000=device(
        'nicos_ess.devices.epics.extensions.EpicsMappedMoveable',
        description='Pause pumping',
        readpv='{}PAUSE'.format(pv_root),
        writepv='{}PAUSE'.format(pv_root),
        mapping={'OFF': 0, 'ON': 1},
    ),
    stop_pumping_9000=device(
        'nicos_ess.devices.epics.extensions.EpicsMappedMoveable',
        description='Stop pumping',
        readpv='{}STOP'.format(pv_root),
        writepv='{}STOP'.format(pv_root),
        mapping={'OFF': 0, 'ON': 1},
    ),
    seconds_to_pause_9000=device(
        'nicos.devices.epics.EpicsAnalogMoveable',
        description='How long to pause for',
        readpv='{}SET_PAUSE'.format(pv_root),
        writepv='{}SET_PAUSE'.format(pv_root),
        epicstimeout=3.0,
        abslimits=(0.1, 50),
    ),
    zero_volume_withdrawn_9000=device(
        'nicos.devices.epics.EpicsReadable',
        description='Zero volume withdrawn and infused',
        readpv='{}CLEAR_V_DISPENSED'.format(pv_root),
        epicstimeout=3.0,
    ),
)
